Feature issue Allow defining shared memory size at runtime #282
eunomia-bpf/bpftime pull request #285
Opened 2024-04-21 08:38 UTC by NobinPegasus

## Description

I have declared `extern size_t BPFTIME_SHARED_MEMORY_SIZE;` inside `bpftime_shm_internal.hpp` and inside `bpftime_shm_internal.cpp` defined the `size_t BPFTIME_SHARED_MEMORY_SIZE = 20; // Default size`

Then inside the cli/main.cpp I have added support for --shared-memory-size.

Fixes #282 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [✅] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- [ ] Test A
- [ ] Test B

**Test Configuration**:

## Checklist

- [✅] My code follows the style guidelines of this project
- [✅] I have performed a self-review of my own code
- [✅] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [✅] I have checked my code and corrected any misspellings

2024-04-24 07:00 UTC, Officeyutong commented
@NobinPegasus Is this PR finished yet? I haven't seen things related to read environment variables

2024-04-25 07:30 UTC, Officeyutong requested changes

2024-04-25 07:30 UTC, Officeyutong commented on tools/cli/main.cpp
> +            BPFTIME_SHARED_MEMORY_SIZE = std::stoi(value); // Convert MB to bytes
Have you tested this program? CLI will not be linked with runtime

2024-08-09 09:07 UTC, yunwei37 commented
What I have done is:

1. Add new env var for shm size 
2. Make the config a separate file 
3. Fix the wrong default value of the config 

Another thing I need to do in the next PR is

- merge the syscall server config with this config 
- rename agent config to bpftime_config, so it's global

2024-08-09 09:27 UTC, merged

2024-08-09 12:50 UTC, Officeyutong commented on runtime/include/bpftime_config.hpp
> +	int shm_memory_size = 20; // 20MB
Will bytes be better?

2024-08-09 12:51 UTC, Officeyutong commented on runtime/src/bpftime_shm_internal.cpp
> +			// Allocate 20M bytes of memory by default
Comment should be updated